export const CATEGORIES = [
  { id: "coffee", label: "coffee shops" },
  { id: "viewpoint", label: "viewpoints" },
  { id: "museum", label: "museums" },
  { id: "instagram", label: "photo walls" },
  { id: "mall", label: "malls" },
  { id: "bar", label: "bars" },
];

export const BUDGETS = [
  { id: 0, label: "free", hint: "walk-up, no till" },
  { id: 5, label: "$5", hint: "snack money" },
  { id: 15, label: "$15", hint: "still cheap" },
];

/** Seeded "nearby" leftovers for a weekend demo. */
export const SPOTS = [
  {
    id: "piano",
    name: "Laundromat piano",
    blurb: "Someone left a slightly-in-tune upright between the dryers. Sit. Fold. Listen.",
    tags: [],
    leftoverOf: "cafés with playlists",
    cost: 0,
    walk: 4,
    friend: false,
  },
  {
    id: "bolts",
    name: "Hardware-store snack counter",
    blurb: "Bolts in aisle 3, $2 steamed buns at the back register. No ambience. Perfect.",
    tags: [],
    leftoverOf: "brunch lines",
    cost: 5,
    walk: 6,
    friend: false,
  },
  {
    id: "ferry",
    name: "Ferry terminal sunset",
    blurb: "You don't need a ticket. The waiting hall faces west and the vending coffee is a crime, in a good way.",
    tags: ["viewpoint"],
    leftoverOf: "rooftop bars",
    cost: 0,
    walk: 11,
    friend: false,
  },
  {
    id: "radio",
    name: "Student radio hallway",
    blurb: "The booth window leaks whatever they're playing. Sit on the radiator. Don't talk.",
    tags: [],
    leftoverOf: "clubs",
    cost: 0,
    walk: 8,
    friend: false,
  },
  {
    id: "chess",
    name: "Park chess with house rules",
    blurb: "The regulars will roast you for free. Winner gets the shady bench.",
    tags: [],
    leftoverOf: "escape rooms",
    cost: 0,
    walk: 5,
    friend: false,
  },
  {
    id: "cart",
    name: "The $2 cart that moved",
    blurb: "Corn, chili, lime. It migrates. Last ping: outside the clinic, not the square.",
    tags: [],
    leftoverOf: "food halls",
    cost: 5,
    walk: 3,
    friend: true,
  },
  {
    id: "bingo",
    name: "Church basement bingo",
    blurb: "Paper cards, bad coffee, extremely high stakes gossip. Cards are a few bucks.",
    tags: [],
    leftoverOf: "trivia nights",
    cost: 5,
    walk: 9,
    friend: false,
  },
  {
    id: "tapes",
    name: "Vinyl shop courtyard",
    blurb: "They play one side all the way through. Sitting is free. Buying is optional and still cheap.",
    tags: [],
    leftoverOf: "record-store selfies",
    cost: 0,
    walk: 7,
    friend: false,
  },
  {
    id: "gallery",
    name: "Last-entry student show",
    blurb: "Sliding scale, often $0 if you look like you mean it. Closes when the volunteer gets hungry.",
    tags: ["museum"],
    leftoverOf: "big museums",
    cost: 5,
    walk: 12,
    friend: false,
  },
  {
    id: "noodles",
    name: "Night-window noodles",
    blurb: "One hatch, three stools, no English menu needed. Under $15 if you don't get cute.",
    tags: [],
    leftoverOf: "ramen queues",
    cost: 15,
    walk: 5,
    friend: false,
  },
  {
    id: "mural",
    name: "The mural they already photographed",
    blurb: "It's fine. You've seen it. The alley behind it has a free echo and a cat.",
    tags: ["instagram", "viewpoint"],
    leftoverOf: "the mural",
    cost: 0,
    walk: 2,
    friend: false,
  },
  {
    id: "mallfood",
    name: "Food court after 8",
    blurb: "Aunties discount the last trays. Fluorescent lighting. Peak cheap thrill.",
    tags: ["mall"],
    leftoverOf: "new restaurants",
    cost: 15,
    walk: 10,
    friend: false,
  },
  {
    id: "espresso",
    name: "Third-wave but make it a line",
    blurb: "Oat this, origin that. You've done this. The leftover is the bakery next door with no chairs.",
    tags: ["coffee"],
    leftoverOf: "coffee",
    cost: 15,
    walk: 3,
    friend: false,
  },
  {
    id: "lookout",
    name: "Official scenic lookout",
    blurb: "The postcard. Buses. You've been. Wind is free, wonder is used up.",
    tags: ["viewpoint", "instagram"],
    leftoverOf: "the view",
    cost: 0,
    walk: 14,
    friend: false,
  },
  {
    id: "rooftop",
    name: "Rooftop with a cover",
    blurb: "Cover charge plus a drink minimum. Pretty. Not a leftover.",
    tags: ["bar", "viewpoint"],
    leftoverOf: "rooftops",
    cost: 15,
    walk: 8,
    friend: false,
  },
  {
    id: "busker",
    name: "Underpass brass",
    blurb: "A trumpet and a wet tile reverb. Tip jar is optional. Best seat is the curb.",
    tags: [],
    leftoverOf: "concert tickets",
    cost: 0,
    walk: 6,
    friend: true,
  },
  {
    id: "zine",
    name: "Zine shelf in the station kiosk",
    blurb: "Folded paper, $3, stories from this block. Read it on the slow bus.",
    tags: [],
    leftoverOf: "bookstores",
    cost: 5,
    walk: 4,
    friend: false,
  },
  {
    id: "fountain",
    name: "Fountain steps after school",
    blurb: "Kids jump the spray. You sit one level up with a bag of peanuts.",
    tags: [],
    leftoverOf: "paid gardens",
    cost: 5,
    walk: 7,
    friend: false,
  },
];

export const LIVE_FINDS = [
  {
    id: "live-hatch",
    name: "Secret bakery hatch",
    blurb: "A friend just found a window that sells day-old pastry for coins. 90 seconds from here.",
    tags: [],
    leftoverOf: "pastry lines",
    cost: 5,
    walk: 2,
    friend: true,
    live: true,
  },
  {
    id: "live-court",
    name: "Empty courtyard + one speaker",
    blurb: "Someone dragged a speaker into a loading dock. It's accidentally a party. Free.",
    tags: [],
    leftoverOf: "ticketed shows",
    cost: 0,
    walk: 5,
    friend: true,
    live: true,
  },
];
